CREATE TABLE IF NOT EXISTS advogado (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    numero_oab VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (cpf),
    UNIQUE (numero_oab)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
